reward, stake, member management test base on local e2e test framework
clearmatics/autonity pull request #594
Opened 2020-06-20 06:20 UTC by Jason-Zhangxin-Chen

It contains e2e test case to cover:
1. reward distribution test with stake changes on the run time.
2. stake management test.
3. member management test.
It would close: 
https://github.com/clearmatics/autonity/issues/412
https://github.com/clearmatics/autonity/issues/590
https://github.com/clearmatics/autonity/issues/587

2020-07-24 14:11 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +func TestRewardDistribution(t *testing.T) {
I think these tests need a lot more description or the code inside them needs to be refactored, or both, to make it easier to follow the flow of what is happening. As it is we have 220 lines of hooks that the reader needs to take into account in and understand when they will be called and in which order in order to know what the test is doing, there is too much setup and complexity in these tests, for a reviewer to be able to give it clear scrutiny. There is also no explanation of what is the expected mechanism of reward distribution.

2020-07-27 09:56 UTC, Jason-Zhangxin-Chen commented on consensus/test/reward_distribution_test.go
> +func TestRewardDistribution(t *testing.T) {
> I think these tests need a lot more description or the code inside them needs to be refactored, or both, to make it easier to follow the flow of what is happening. As it is we have 220 lines of hooks that the reader needs to take into account in and understand when they will be called and in which order in order to know what the test is doing, there is too much setup and complexity in these tests, for a reviewer to be able to give it clear scrutiny. There is also no explanation of what is the expected mechanism of reward distribution.

For our golang based local e2e test framework, it do use a lots of hook functions to do the condition preparation, behavior simulation, and out put checking, it introduce the complexity but still understandable. 
Let me know which part is not clear, I will try to refine them.

2020-08-25 15:01 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +func TestRewardDistribution(t *testing.T) {
Could you start by providing a comment for each test explaining in simple terms what is the flow of the test and what it is checking.

2020-08-25 15:17 UTC, piersy requested changes
I left my suggestions in my last comment.

2020-08-26 04:17 UTC, Jason-Zhangxin-Chen commented
> I left my suggestions in my last comment.

Hi Piers, I add case level comments on how those test work flow works, please take a review and try to understand the workflow.

2020-08-27 16:32 UTC, piersy commented on consensus/test/member_management_test.go
> +			}
Hi @Jason-Zhangxin-Chen, I can see this block repeated 10 times throughout these tests.

Could you refactor it into a function that accepts the private key of the transaction sender and returns the autonity contract instance and auth, I think this would make the code a lot easier to follow.

E.G:
```golang
func autonityInstance(callerKey ecdsa.PrivateKey) (*Autonity, *TransactOpts)
```

2020-08-28 08:40 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +			}
@piersy , it is resolved now. Please refer to my last commit which refines it.

2020-08-28 14:58 UTC, piersy commented on consensus/test/stake_management_test.go
> +func autonityInstance(t *testing.T, operatorKey *ecdsa.PrivateKey, node *testNode) (*Autonity, *bind.TransactOpts, *ethclient.Client, error) {
instead of returning the  `*ethclient.Client` just so that we can close it at the right time, I think it would be neater if we introduced a struct.

```golang
type testAutonity struct {
  *Autonity
  client *ethclient.Client
}
```

Note the Autonity instance is embedded, and then we just add a `Close` method on the struct that calls close on the internal client. This saves callers of `autonityInstance` from needing to pass around both the Autonity instance and the ethclient.Client instance.

Also it doesn't make sense to pass `t` to this function but still return an error, if you are passing `t` you can call `t.Fatal` inside the function and avoid returning errors.

2020-08-28 16:01 UTC, piersy commented on consensus/test/stake_management_test.go
> +	//auth.GasLimit = uint64(300000) // in units
```suggestion
```

2020-08-28 16:03 UTC, piersy commented on consensus/test/stake_management_test.go
> +		auth := bind.CallOpts{
Why can't we use the auth from autonityInstance here?

2020-08-28 16:12 UTC, piersy commented on consensus/test/stake_management_test.go
> +	instance, err := NewAutonity(contractAddress, conn)
```suggestion
	instance, err := NewAutonity(autonity.ContractAddress, conn)
```

2020-08-28 16:14 UTC, piersy commented on consensus/test/member_management_test.go
> +	}
Lets use testify's assert and require instead. They help cut down the noise in tests,
```suggestion
	require.NoiError(t, err)
```

2020-08-28 16:15 UTC, piersy requested changes
Requested changes are in the comments.

2020-09-01 07:43 UTC, Jason-Zhangxin-Chen commented on consensus/test/stake_management_test.go
> +		auth := bind.CallOpts{
> Why can't we use the auth from autonityInstance here?

Reading and Writing from contract, they use different type of "auth" which have different type: bind.CallOpts and bind.TransactOpt to specific the context.

2020-09-01 08:27 UTC, Jason-Zhangxin-Chen commented on consensus/test/stake_management_test.go
> +		auth := bind.CallOpts{
> > Why can't we use the auth from autonityInstance here?
> 
> I will refine this two by wrapping them into testAutonity to make it a better view.

2020-09-01 15:19 UTC, piersy commented on consensus/test/stake_management_test.go
> +	if a.client != nil {
Instead of checking for nil here we should just make sure we always provide a non nil client when creating testAutonity

2020-09-01 15:20 UTC, piersy commented on consensus/test/stake_management_test.go
> +func autonityInstance(operatorKey *ecdsa.PrivateKey, node *testNode) (*testAutonity, error) {
Instead of passing in the `node` lets just pass in the port, since that is all that is needed.

2020-09-01 15:28 UTC, piersy commented on consensus/test/stake_management_test.go
> +	autonity       *Autonity
I think we should embed `*Autonity`, then users of test autonity can use it in the same way that they would use `*Autonity`

2020-09-01 16:16 UTC, piersy commented on consensus/test/stake_management_test.go
> +	callOpt        *bind.CallOpts
Rather than setting transactionOpt and callOpt fields I think it would be nicer if we instead added methods to testAutonity that generate the opts when called. This would allow us to query the nonce and suggested gas price at the point of transaction submission, and it also removes the chance that someone tries to use the `callOpt` without setting the block.

E.G:
```golang
func (a *testAutonity) transactionOpts() (*bind.transactionOpts, error){
....
}

func (a *testAutonity) callOpts(uint64 blockNumber) (*bind.CallOpts){
....
}


```

2020-09-01 16:19 UTC, piersy commented on consensus/test/member_management_test.go
> +		instance, err := NewAutonity(contractAddress, conn)
I can see this and 3 other calls to `NewAutonity` that I think could be replaced with `autonityInstance`

2020-09-01 16:22 UTC, piersy commented on consensus/test/stake_management_test.go
> +	instance, err := NewAutonity(contractAddress, conn)
@Jason-Zhangxin-Chen I can see still a few instances of this assignment.

2020-09-01 16:24 UTC, piersy commented on consensus/test/member_management_test.go
> +	}
Hi @Jason-Zhangxin-Chen, in my previous comment I meant lets use testify and assert for all of our assertions in these tests, not just the specific case I picked out.

2020-09-01 16:29 UTC, piersy commented on consensus/test/stake_management_test.go
> +func autonityInstance(operatorKey *ecdsa.PrivateKey, node *testNode) (*testAutonity, error) {
I think it would be clearer to put this function and `testAutonity` inside `test_helpers_test.go` since it is called from all of these test files, so it seems arbitrary to just define it in one test file.

2020-09-02 16:53 UTC, aneequesafdar commented on consensus/test/stake_management_test.go
> +	}
I am not sure why you want to set the client if Dial fails?

```suggestion
	conn, err := ethclient.Dial("http://127.0.0.1:" + strconv.Itoa(node.rpcPort))
	if err != nil {
		return contract, err
	}	
	contract.client = conn
```
```suggestion
	conn, err := ethclient.Dial("http://127.0.0.1:" + strconv.Itoa(node.rpcPort))
	contract.client = conn
	if err != nil {
		return contract, err
	}
```

2020-09-03 07:05 UTC, Jason-Zhangxin-Chen commented
@piersy @aneequesafdar , thanks for yesterday's comments, the code looks much better now.

2020-09-03 12:18 UTC, piersy commented on consensus/test/member_management_test.go
> +		instance, err := NewAutonity(contractAddress, conn)
@Jason-Zhangxin-Chen  I can still see these calls to `NewAutonity`.

2020-09-03 12:51 UTC, piersy commented on consensus/test/member_management_test.go
> +				t.Fatal(err)
@Jason-Zhangxin-Chen, you can't use `t.Fatal` inside any beforeHooks, afterHooks or sendTransactionHooks, because they are all run in a different goroutine to the main test goroutine.

You need to return the errors in these cases.

2020-09-03 12:54 UTC, piersy commented on consensus/test/member_management_test.go
> +		once.Do(func() {
Why not do this? It seems simpler.

```suggestion
		if validator.lastBlock == 4 {
```

2020-09-03 13:06 UTC, piersy commented on consensus/test/member_management_test.go
> +		}
```suggestion
		assert.Contains(t, whiteList, eNode)
```

2020-09-03 13:14 UTC, piersy commented on consensus/test/member_management_test.go
> +				}
```suggestion
				assert.Equal(t, curNetworkMetrics.Stakes[index], stakeBalance,
					"new validator's stake is not expected")
```

2020-09-03 13:16 UTC, piersy commented on consensus/test/member_management_test.go
> +				}
```suggestion
				assert.Equal(t, curNetworkMetrics.Usertypes[index], 2,
					"new validator's user type is not expected")
```

2020-09-03 13:27 UTC, piersy requested changes
Hi @Jason-Zhangxin-Chen I left a number of suggestions for using testify's `assert` package to streamline your checks, If you look at your code I think you will be able to find a number of other places where you could streamline your checks with the use of the `assert` package.

2020-09-03 13:34 UTC, piersy commented on consensus/test/member_management_test.go
> +				founded = true
```suggestion
		found := false
		for index, v := range curNetworkMetrics.Accounts {
			if v == crypto.PubkeyToAddress(newValidatorKey.PublicKey) {
				found = true
```

Found is the past tense of find, founded means something else.

2020-09-03 15:05 UTC, aneequesafdar commented on consensus/test/member_management_test.go
> +			eNode := enode.V4DNSUrl(newValidatorKey.PublicKey, "VN:8527", 8527, 8527)
Can someone please explain what does `enode.V4DNSUrl` do, especially the significance of "VN:8527" parameter?

2020-09-03 15:13 UTC, aneequesafdar commented on consensus/test/member_management_test.go
> +	require.NoError(t, err)
In all the usages of `newValidatorKey` you are only using the public key, so please apply the following changes
```suggestion
	newValidatorKey, err := keygenerator.Next()
	require.NoError(t, err)
	newValidatorPubKey := newValidatorKey.PublicKey
```
After this please replace all usages of `newValidatorKey.PublicKey` with `newValidatorPubKey`

2020-09-03 15:19 UTC, aneequesafdar commented on consensus/test/member_management_test.go
> +				t.Fatal(err)
There is already a error return value, so please use that to return the error to the caller

2020-09-03 15:20 UTC, aneequesafdar commented on consensus/test/member_management_test.go
> +		instance, err := NewAutonity(contractAddress, conn)
I agree with @piersy these lines can be simplified similar to line 58

2020-09-03 15:23 UTC, aneequesafdar commented on consensus/test/member_management_test.go
> +		}
please use `testAutonity.callOpts()`

2020-09-03 16:04 UTC, aneequesafdar commented
I don't think `TestMemberManagementAddNewValidator`, `TestMemberManagementAddNewStakeHolder` and `TestMemberManagementAddNewParticipant` should be three different tests each with its own specific function, all of these test share everything except the type of participant. Therefore, I would rather have a single test such as (this would massively reduce duplication)

```go
func TestMemberManagementAddition(t *testing.T) {
	// set up of hooks, which should be refactored since they share virtually the same code
	cases := []*testCase{
		{
			name:          "member management test add validator",
			numValidators: 6,
			numBlocks:     20,
			txPerPeer:     1,
			sendTransactionHooks: map[string]func(validator *testNode, fromAddr common.Address, toAddr common.Address) (bool, *types.Transaction, error){
				"VA": addValidatorHook,
			},
			genesisHook: genesisHook,
			finalAssert: addValidatorCheckerHook,
		},
		{
			name:          "member management test add stakeholder",
			numValidators: 6,
			numBlocks:     20,
			txPerPeer:     1,
			sendTransactionHooks: map[string]func(validator *testNode, fromAddr common.Address, toAddr common.Address) (bool, *types.Transaction, error){
				"VA": addStakeHolderHook,
			},
			genesisHook: genesisHook,
			finalAssert: addStakeHolderCheckerHook,
		},
		{
			name:          "member management test add participant",
			numValidators: 6,
			numBlocks:     20,
			txPerPeer:     1,
			sendTransactionHooks: map[string]func(validator *testNode, fromAddr common.Address, toAddr common.Address) (bool, *types.Transaction, error){
				"VA": addParticipantHook,
			},
			genesisHook: genesisHook,
			finalAssert: addParticipantCheckerHook,
		},
	}

	for _, testCase := range cases {
		testCase := testCase
		t.Run(fmt.Sprintf("test case %s", testCase.name), func(t *testing.T) {
			runTest(t, testCase)
		})
	}

}
```

2020-09-03 16:17 UTC, piersy commented on consensus/test/member_management_test.go
> +			eNode := enode.V4DNSUrl(newValidatorKey.PublicKey, "VN:8527", 8527, 8527)
Its badly named, it makes an enode string from the public key and the "dns" parameter which is actually just a host or host and port. it should probably be moved into the test helpers since we only use it in tests and it will cause conflicts with upstream merges being in `urlv4.go`. In this case "VN:8527" is the host and port. The test framework requires that the hostname of a node defines the node type with the initial char V for validator P for participant S for stakeholder, the char that follows is just the name of that node. In this case I guess it is N for new. The test framework also sets a custom resolver for hostnames so that things like "VN" acatually resolve to localhost.

2020-09-03 16:40 UTC, aneequesafdar commented on consensus/test/reward_distribution_test.go
> +		type EconomicMetaData struct {
this should be private: `economicMetaData`. Since it is only used in one place.

2020-09-03 17:47 UTC, aneequesafdar commented on consensus/test/reward_distribution_test.go
> +				make([]*big.Int, 32), new(big.Int), new(big.Int)}
What is the significance of 32, we don't have 32 validators for this test case, right?

2020-09-03 17:49 UTC, aneequesafdar commented on consensus/test/reward_distribution_test.go
> +				make([]*big.Int, 32), new(big.Int), new(big.Int)}
Also, I am not sure whether you have to initialise each of the fields.  `parentEconomicState = &EconomicState{}` should be sufficient.

2020-09-03 17:57 UTC, aneequesafdar commented on consensus/test/reward_distribution_test.go
> +	rewardChecker := rewardCheckHookGenerator()
I am not sure why you have three levels of function variable indirection when they are only used in one place please update 
```suggestion
// reward checker hook:
	rewardCheckerHook := func(block *types.Block, validator *testNode, tCase *testCase, currentTime time.Time) error {
		type economicMetaData struct {
			Accounts        []common.Address `abi:"accounts"`
			Usertypes       []uint8          `abi:"usertypes"`
			Stakes          []*big.Int       `abi:"stakes"`
			Commissionrates []*big.Int       `abi:"commissionrates"`
			Mingasprice     *big.Int         `abi:"mingasprice"`
			Stakesupply     *big.Int         `abi:"stakesupply"`
		}
		// each new mined block will be checked by reward distribution checking.
		// reward distribution checking start from height-2.
		if block.NumberU64() < 2 {
			return nil
		}
		blockReward := new(big.Int)
		gp := new(core.GasPool).AddGas(block.GasLimit())
		parent := validator.service.BlockChain().GetBlock(block.ParentHash(), block.NumberU64()-1)

		addr := crypto.PubkeyToAddress(validator.privateKey.PublicKey)
		// get parent block view.
		parentState, stateErr := validator.service.BlockChain().StateAt(parent.Root())
		if stateErr != nil {
			return stateErr
		}
		balanceBase := parentState.GetBalance(addr)
		// calculate sent, gasUsed, receive amount and reward base on new block.
		sentAmount := new(big.Int)
		receivedAmount := new(big.Int)
		usedGas := new(big.Int)
		rewardFraction := new(big.Int)
		for i, tx := range block.Transactions() {
			// Apply TX to parent view again to estimate the gasUsed of the TX.
			parentState.Prepare(tx.Hash(), block.Hash(), i)
			receipt, receiptErr := core.ApplyTransaction(validator.service.BlockChain().Config(), validator.service.BlockChain(), nil, gp, parentState, block.Header(), tx, new(uint64), *validator.service.BlockChain().GetVMConfig())
			if receiptErr != nil {
				return receiptErr
			}

			// count block reward.
			txGasConsumed := new(big.Int).Mul(tx.GasPrice(), new(big.Int).SetUint64(receipt.GasUsed))
			blockReward.Add(blockReward, txGasConsumed)

			// count received amount on the block.
			if *tx.To() == addr {
				receivedAmount.Add(receivedAmount, tx.Value())
			}

			// count sent and gasUsed amount on the block.
			validator.transactionsMu.Lock()
			if _, ok := validator.transactions[tx.Hash()]; ok {
				sentAmount.Add(sentAmount, tx.Value())
				usedGas.Add(usedGas, txGasConsumed)
			}
			validator.transactionsMu.Unlock()
		}

		// calculate reward fractions.
		parentEcomonimcState := economicMetaData{make([]common.Address, 32), make([]uint8, 32), make([]*big.Int, 32),
			make([]*big.Int, 32), new(big.Int), new(big.Int)}
		err := validator.service.BlockChain().GetAutonityContract().AutonityContractCall(parentState, parent.Header(), "dumpEconomicsMetricData", &parentEcomonimcState)
		if err != nil {
			return err
		}

		for i := 0; i < len(parentEcomonimcState.Accounts); i++ {
			if addr == parentEcomonimcState.Accounts[i] {
				rewardFraction = new(big.Int).Mul(blockReward, parentEcomonimcState.Stakes[i])
				rewardFraction = rewardFraction.Div(rewardFraction, parentEcomonimcState.Stakesupply)
				break
			}
		}

		// current block view.
		currentState, stateErr := validator.service.BlockChain().StateAt(block.Root())
		if stateErr != nil {
			return stateErr
		}
		balanceActual := currentState.GetBalance(addr)
		// check if balance is expected: base + reward + received - sent - gasUsed == bActual.
		balanceWant := new(big.Int).Add(balanceBase, rewardFraction)
		balanceWant.Add(balanceWant, receivedAmount)
		balanceWant.Sub(balanceWant, sentAmount)
		balanceWant.Sub(balanceWant, usedGas)
		if balanceWant.Cmp(balanceActual) != 0 {
			return fmt.Errorf("rewardFraction distribution might in-correct")
		}
		return nil
	}
```

2020-09-03 17:57 UTC, aneequesafdar commented on consensus/test/reward_distribution_test.go
> +	rewardChecker := rewardCheckHookGenerator()
I am not sure why you have three levels of function variable indirection when they are only used in one place please update 
```suggestion
// reward checker hook:
	rewardCheckerHook := func(block *types.Block, validator *testNode, tCase *testCase, currentTime time.Time) error {
		type economicMetaData struct {
			Accounts        []common.Address `abi:"accounts"`
			Usertypes       []uint8          `abi:"usertypes"`
			Stakes          []*big.Int       `abi:"stakes"`
			Commissionrates []*big.Int       `abi:"commissionrates"`
			Mingasprice     *big.Int         `abi:"mingasprice"`
			Stakesupply     *big.Int         `abi:"stakesupply"`
		}
		// each new mined block will be checked by reward distribution checking.
		// reward distribution checking start from height-2.
		if block.NumberU64() < 2 {
			return nil
		}
		blockReward := new(big.Int)
		gp := new(core.GasPool).AddGas(block.GasLimit())
		parent := validator.service.BlockChain().GetBlock(block.ParentHash(), block.NumberU64()-1)

		addr := crypto.PubkeyToAddress(validator.privateKey.PublicKey)
		// get parent block view.
		parentState, stateErr := validator.service.BlockChain().StateAt(parent.Root())
		if stateErr != nil {
			return stateErr
		}
		balanceBase := parentState.GetBalance(addr)
		// calculate sent, gasUsed, receive amount and reward base on new block.
		sentAmount := new(big.Int)
		receivedAmount := new(big.Int)
		usedGas := new(big.Int)
		rewardFraction := new(big.Int)
		for i, tx := range block.Transactions() {
			// Apply TX to parent view again to estimate the gasUsed of the TX.
			parentState.Prepare(tx.Hash(), block.Hash(), i)
			receipt, receiptErr := core.ApplyTransaction(validator.service.BlockChain().Config(), validator.service.BlockChain(), nil, gp, parentState, block.Header(), tx, new(uint64), *validator.service.BlockChain().GetVMConfig())
			if receiptErr != nil {
				return receiptErr
			}

			// count block reward.
			txGasConsumed := new(big.Int).Mul(tx.GasPrice(), new(big.Int).SetUint64(receipt.GasUsed))
			blockReward.Add(blockReward, txGasConsumed)

			// count received amount on the block.
			if *tx.To() == addr {
				receivedAmount.Add(receivedAmount, tx.Value())
			}

			// count sent and gasUsed amount on the block.
			validator.transactionsMu.Lock()
			if _, ok := validator.transactions[tx.Hash()]; ok {
				sentAmount.Add(sentAmount, tx.Value())
				usedGas.Add(usedGas, txGasConsumed)
			}
			validator.transactionsMu.Unlock()
		}

		// calculate reward fractions.
		parentEcomonimcState := economicMetaData{make([]common.Address, 32), make([]uint8, 32), make([]*big.Int, 32),
			make([]*big.Int, 32), new(big.Int), new(big.Int)}
		err := validator.service.BlockChain().GetAutonityContract().AutonityContractCall(parentState, parent.Header(), "dumpEconomicsMetricData", &parentEcomonimcState)
		if err != nil {
			return err
		}

		for i := 0; i < len(parentEcomonimcState.Accounts); i++ {
			if addr == parentEcomonimcState.Accounts[i] {
				rewardFraction = new(big.Int).Mul(blockReward, parentEcomonimcState.Stakes[i])
				rewardFraction = rewardFraction.Div(rewardFraction, parentEcomonimcState.Stakesupply)
				break
			}
		}

		// current block view.
		currentState, stateErr := validator.service.BlockChain().StateAt(block.Root())
		if stateErr != nil {
			return stateErr
		}
		balanceActual := currentState.GetBalance(addr)
		// check if balance is expected: base + reward + received - sent - gasUsed == bActual.
		balanceWant := new(big.Int).Add(balanceBase, rewardFraction)
		balanceWant.Add(balanceWant, receivedAmount)
		balanceWant.Sub(balanceWant, sentAmount)
		balanceWant.Sub(balanceWant, usedGas)
		if balanceWant.Cmp(balanceActual) != 0 {
			return fmt.Errorf("rewardFraction distribution might in-correct")
		}
		return nil
	}
```

2020-09-03 17:57 UTC, aneequesafdar commented on consensus/test/reward_distribution_test.go
> +	rewardChecker := rewardCheckHookGenerator()
I am not sure why you have three levels of function variable indirection when they are only used in one place please update 
```suggestion
// reward checker hook:
	rewardCheckerHook := func(block *types.Block, validator *testNode, tCase *testCase, currentTime time.Time) error {
		type economicMetaData struct {
			Accounts        []common.Address `abi:"accounts"`
			Usertypes       []uint8          `abi:"usertypes"`
			Stakes          []*big.Int       `abi:"stakes"`
			Commissionrates []*big.Int       `abi:"commissionrates"`
			Mingasprice     *big.Int         `abi:"mingasprice"`
			Stakesupply     *big.Int         `abi:"stakesupply"`
		}
		// each new mined block will be checked by reward distribution checking.
		// reward distribution checking start from height-2.
		if block.NumberU64() < 2 {
			return nil
		}
		blockReward := new(big.Int)
		gp := new(core.GasPool).AddGas(block.GasLimit())
		parent := validator.service.BlockChain().GetBlock(block.ParentHash(), block.NumberU64()-1)

		addr := crypto.PubkeyToAddress(validator.privateKey.PublicKey)
		// get parent block view.
		parentState, stateErr := validator.service.BlockChain().StateAt(parent.Root())
		if stateErr != nil {
			return stateErr
		}
		balanceBase := parentState.GetBalance(addr)
		// calculate sent, gasUsed, receive amount and reward base on new block.
		sentAmount := new(big.Int)
		receivedAmount := new(big.Int)
		usedGas := new(big.Int)
		rewardFraction := new(big.Int)
		for i, tx := range block.Transactions() {
			// Apply TX to parent view again to estimate the gasUsed of the TX.
			parentState.Prepare(tx.Hash(), block.Hash(), i)
			receipt, receiptErr := core.ApplyTransaction(validator.service.BlockChain().Config(), validator.service.BlockChain(), nil, gp, parentState, block.Header(), tx, new(uint64), *validator.service.BlockChain().GetVMConfig())
			if receiptErr != nil {
				return receiptErr
			}

			// count block reward.
			txGasConsumed := new(big.Int).Mul(tx.GasPrice(), new(big.Int).SetUint64(receipt.GasUsed))
			blockReward.Add(blockReward, txGasConsumed)

			// count received amount on the block.
			if *tx.To() == addr {
				receivedAmount.Add(receivedAmount, tx.Value())
			}

			// count sent and gasUsed amount on the block.
			validator.transactionsMu.Lock()
			if _, ok := validator.transactions[tx.Hash()]; ok {
				sentAmount.Add(sentAmount, tx.Value())
				usedGas.Add(usedGas, txGasConsumed)
			}
			validator.transactionsMu.Unlock()
		}

		// calculate reward fractions.
		parentEcomonimcState := economicMetaData{make([]common.Address, 32), make([]uint8, 32), make([]*big.Int, 32),
			make([]*big.Int, 32), new(big.Int), new(big.Int)}
		err := validator.service.BlockChain().GetAutonityContract().AutonityContractCall(parentState, parent.Header(), "dumpEconomicsMetricData", &parentEcomonimcState)
		if err != nil {
			return err
		}

		for i := 0; i < len(parentEcomonimcState.Accounts); i++ {
			if addr == parentEcomonimcState.Accounts[i] {
				rewardFraction = new(big.Int).Mul(blockReward, parentEcomonimcState.Stakes[i])
				rewardFraction = rewardFraction.Div(rewardFraction, parentEcomonimcState.Stakesupply)
				break
			}
		}

		// current block view.
		currentState, stateErr := validator.service.BlockChain().StateAt(block.Root())
		if stateErr != nil {
			return stateErr
		}
		balanceActual := currentState.GetBalance(addr)
		// check if balance is expected: base + reward + received - sent - gasUsed == bActual.
		balanceWant := new(big.Int).Add(balanceBase, rewardFraction)
		balanceWant.Add(balanceWant, receivedAmount)
		balanceWant.Sub(balanceWant, sentAmount)
		balanceWant.Sub(balanceWant, usedGas)
		if balanceWant.Cmp(balanceActual) != 0 {
			return fmt.Errorf("rewardFraction distribution might in-correct")
		}
		return nil
	}
```

2020-09-03 17:58 UTC, aneequesafdar commented on consensus/test/reward_distribution_test.go
> +	rewardChecker := rewardCheckHookGenerator()
I am not sure why you have three levels of function variable indirection when they are only used in one place please update 
```go
// reward checker hook:
rewardCheckerHook := func(block *types.Block, validator *testNode, tCase *testCase, currentTime time.Time) error {...}
```

2020-09-03 18:01 UTC, aneequesafdar commented on consensus/test/reward_distribution_test.go
> +				return fmt.Errorf("rewardFraction distribution might in-correct")
```suggestion
				return fmt.Errorf("incorrect reward distribution")
```

2020-09-03 18:05 UTC, aneequesafdar commented on consensus/test/reward_distribution_test.go
> +		}
surely this block of code can be refactored in `mintStakeHook`, `transferStakeHook` and `redeemStakeHook`

2020-09-04 06:34 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +		once.Do(func() {
@piersy , thank you, Piers. I refine all of them in my last commit of today.

2020-09-04 06:36 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +				t.Fatal(err)
Thank you for the findings, @piersy @aneequesafdar , I fix them in my lastest commit today.

2020-09-04 08:18 UTC, Jason-Zhangxin-Chen commented on consensus/test/reward_distribution_test.go
> +				make([]*big.Int, 32), new(big.Int), new(big.Int)}
Yes, it works if we use parentEconomicState = &EconomicState{}

2020-09-04 09:05 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +		type EconomicMetaData struct {
I don't think it really makes a difference, the type is only accessible inside the scope of the hook, and also you cannot import test code so, even if this was defined at package scope, it would only be accessible in these tests.

2020-09-04 12:40 UTC, piersy commented on consensus/test/testcase_test.go
>  	}
`finalAssert` was being run in the main test goroutine, so we don't need to make this change, because you can call `t.Fatal` inside it.

This means we can also remove the changes to - `autonity_contract_test.go`

2020-09-04 12:41 UTC, piersy commented on consensus/test/member_management_test.go
> +		instance, err := NewAutonity(contractAddress, conn)
@Jason-Zhangxin-Chen I can still see this and one other call to `NewAutonity` that could be replaced with `autonityInstance`

2020-09-04 14:08 UTC, piersy commented on consensus/test/member_management_test.go
> +	}
@Jason-Zhangxin-Chen I can still see some ocurrences of `t.Fatal`

2020-09-04 14:56 UTC, Jason-Zhangxin-Chen commented
@aneequesafdar , @piersy , thanks a lots for your suggestions, it is a great experience when I refine those findings to the things we have right now, it helps to improve my skill of golang. 
Please review it the latest commit here, and leave your comments.

2020-09-04 15:23 UTC, Jason-Zhangxin-Chen commented
> I don't think `TestMemberManagementAddNewValidator`, `TestMemberManagementAddNewStakeHolder`, `TestMemberManagementAddNewParticipant` and `TestMemberManagementRemoveUser` should be four different tests each with its own specific function, all of these test share everything except the type of participant. Therefore, I would rather have a single test such as (this would massively reduce duplication)
> 
> ```go
> func TestMemberManagement(t *testing.T) {
> 	// set up of hooks, which should be refactored since they share virtually the same code
> 	cases := []*testCase{
> 		{
> 			name:          "add validator",
> 			numValidators: 6,
> 			numBlocks:     20,
> 			txPerPeer:     1,
> 			sendTransactionHooks: map[string]func(validator *testNode, fromAddr common.Address, toAddr common.Address) (bool, *types.Transaction, error){
> 				"VA": addValidatorHook,
> 			},
> 			genesisHook: genesisHook,
> 			finalAssert: addValidatorCheckerHook,
> 		},
> 		{
> 			name:          "add stakeholder",
> 			numValidators: 6,
> 			numBlocks:     20,
> 			txPerPeer:     1,
> 			sendTransactionHooks: map[string]func(validator *testNode, fromAddr common.Address, toAddr common.Address) (bool, *types.Transaction, error){
> 				"VA": addStakeHolderHook,
> 			},
> 			genesisHook: genesisHook,
> 			finalAssert: addStakeHolderCheckerHook,
> 		},
> 		{
> 			name:          "add participant",
> 			numValidators: 6,
> 			numBlocks:     20,
> 			txPerPeer:     1,
> 			sendTransactionHooks: map[string]func(validator *testNode, fromAddr common.Address, toAddr common.Address) (bool, *types.Transaction, error){
> 				"VA": addParticipantHook,
> 			},
> 			genesisHook: genesisHook,
> 			finalAssert: addParticipantCheckerHook,
> 		},
> 		{
> 			name:          "remove user",
> 			numValidators: 6,
> 			numBlocks:     20,
> 			txPerPeer:     1,
> 			removedPeers:  make(map[common.Address]uint64),
> 			sendTransactionHooks: map[string]func(validator *testNode, fromAddr common.Address, toAddr common.Address) (bool, *types.Transaction, error){
> 				"VD": removeUserHook,
> 			},
> 			genesisHook: genesisHook,
> 			finalAssert: removeUserCheckerHook,
> 		},
> 	}
> 
> 	for _, testCase := range cases {
> 		testCase := testCase
> 		t.Run(fmt.Sprintf("test case %s", testCase.name), func(t *testing.T) {
> 			runTest(t, testCase)
> 		})
> 	}
> }
> ```

Refined it in the same way.

2020-09-04 18:00 UTC, piersy commented on consensus/test/testcase_test.go
>  	}
Hi @Jason-Zhangxin-Chen, this is not resolved, we should not be changing the function signature of final assert in this PR

2020-09-04 18:05 UTC, piersy commented on consensus/test/member_management_test.go
> +	}
```suggestion
	require.NoError(t, err)
```

2020-09-04 18:05 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +	}
```suggestion
	require.NoError(t, err)
```

2020-09-04 18:06 UTC, piersy commented on consensus/test/stake_management_test.go
> +	}
```suggestion
	require.NoError(t, err)
```

2020-09-04 18:19 UTC, piersy commented
Hi @Jason-Zhangxin-Chen, I opened a PR onto this one, it shows an approach to interacting with autonity which I think could really cut down the amount of code we have here. Please check it out #665

2020-09-07 09:38 UTC, piersy commented on consensus/test/autonity_interactor_test.go
> +// tx returns an transactor through which transactions can be executed.
```suggestion
// tx returns a transactor through which transactions can be executed.
```

2020-09-07 09:38 UTC, piersy commented on consensus/test/autonity_interactor_test.go
> +// call returns an caller through which we can call methods of the autonity
```suggestion
// call returns a caller through which we can call methods of the autonity
```

2020-09-07 10:40 UTC, Jason-Zhangxin-Chen commented
@aneequesafdar @yazzaoui @piersy , please review this PR, now the testcase looks leaner than before with a wapping of autonity contract caller.

2020-09-07 14:55 UTC, piersy commented
@aneequesafdar That is because we force pushed on develop. So this branch now contains the changes that we removed from develop, so now we need to rebase this back onto the new develop to see just the relevant changes.

2020-09-07 15:27 UTC, piersy commented
@Jason-Zhangxin-Chen there are still unresolved comments on this PR, please could you check all the unresolved comments and try to resolve them.

2020-09-07 16:31 UTC, aneequesafdar commented on consensus/test/autonity_interactor_test.go
> +// whitelist,err := autonityInstance(rpcPort).call(blockNumber).getWhitelist()
are you sure its not supposed to be:
```suggestion
// err := interact(rpcPort).tx(senderKey).addValidator(address ,stake, enode)
//
// whitelist,err := interact(rpcPort).call(blockNumber).getWhitelist()
```

2020-09-07 16:35 UTC, aneequesafdar commented on consensus/test/autonity_interactor_test.go
> +	err      error
What is the purpose of storing the error inside a struct?

2020-09-07 16:49 UTC, aneequesafdar commented on consensus/test/autonity_interactor_test.go
> +	err      error
The question was a bit premature, I understand how and why it is being used

2020-09-07 18:41 UTC, aneequesafdar commented on consensus/test/member_management_test.go
> +		}
This piece of code is common between `addValidatorCheckerHook`, `addStakeHolderCheckerHook` and `addParticipantCheckerHook`, this should be refactored through a function which probably take stake and user type as parameters

2020-09-08 06:21 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +		}
> This piece of code is common between `addValidatorCheckerHook`, `addStakeHolderCheckerHook` and `addParticipantCheckerHook`, this should be refactored through a function which probably take stake and user type as parameters

I thought it before, but the typing of these hook functions are shared through out the testcases in the framework, adding new parameter would fails all of the other testcaes. making it hard to be extended for such case.

2020-09-08 06:58 UTC, Jason-Zhangxin-Chen commented on consensus/test/testcase_test.go
>  	}
@piersy , in my last commit: https://github.com/clearmatics/autonity/pull/594/commits/b2557a2f88e419eba0de53e543f876389c55659b, I resolve this one, please review it. I think this is the last open comments from you. If everyting is fine, prease approve it, thanks.

2020-09-08 06:59 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +		}
> > This piece of code is common between `addValidatorCheckerHook`, `addStakeHolderCheckerHook` and `addParticipantCheckerHook`, this should be refactored through a function which probably take stake and user type as parameters
> 
> I thought it before, but the typing of these hook functions are shared through out the testcases in the framework, adding new parameter would fails all of the other testcases. It is hard to do so.

2020-09-08 07:00 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +		}
> This piece of code is common between `addValidatorCheckerHook`, `addStakeHolderCheckerHook` and `addParticipantCheckerHook`, this should be refactored through a function which probably take stake and user type as parameters

I thought it before, but the typing of these hook functions are shared through out the testcases in the framework, adding new parameter would fails all of the other testcases. It is hard to do so.

2020-09-08 09:24 UTC, piersy commented on consensus/test/member_management_test.go
> +		}
So now I can see what is going on more clearly in this test. I can see we are basically doing the same thing 3 times, once for validator, once for stakeholder and once for participant. Under the hood all those functions actually call the same function just with a different UserType parameter. That is a bad design because it prevents us writing generic code that simply accepts the UserType parameter. We can see it here because it is forcing us to write 3 times more code than we need to test it. It will have the same effect on people trying to integrate with the system, they will also end up duplicating things 3 times over to account for these 3 methods that do the same thing. The same problem is repeated with the events (having 3 different types of event for the three different user types).

So instead I suggest we make an AddUser fucntion in the autonity contract that accepts UserType as a parameter and remove the AddValidator, AddStakeholder and AddParticipant methods.

Then we can just test AddUser

2020-09-08 09:52 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +		}
Why not add this into the interactor?

2020-09-08 10:04 UTC, Jason-Zhangxin-Chen commented on consensus/test/reward_distribution_test.go
> +		}
> Why not add this into the interactor?

In reward distribution test, since we use state DB directly to calculate those TXs, Gas, Fees changes per block between accounts, etc... So I used to call it directly from state DB rather than the RPC, I think this way would much faster than RPC.

2020-09-08 13:42 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +			return nil
Why do you start from block 2?

2020-09-08 15:40 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +			}
Instead of re-applying the txs to find the receipt lets use `ethclient.TransactionReceipt` to find the actual receipt for that block.

2020-09-08 15:57 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +		}
Rather than getting the parent and then finding the balance from it, I think it is clearer to use the `ethclient.BalanceAt`

2020-09-08 16:01 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +		}
I think we can avoid using the statedb directly by using ethclient instead, and then here we can use the interactor, which saves us from having two different ways of achieving the same thing.

This approach may be much faster than calling via the RPC, but given that nodes wait a second between blocks and this tests specifies 30 blocks, I think the effect on the time taken to run this test of switching to the interactor would be imperceptible.

2020-09-08 16:04 UTC, piersy commented on consensus/test/stake_management_test.go
> +			return true, nil, interact(validator.rpcPort).tx(operatorKey).mintStake(*validatorsList[0].Address, stakeDelta)
```suggestion
	mintStakeHook := func(validator *testNode, address common.Address, _ common.Address) (bool, *types.Transaction, error) { //nolint
		if validator.lastBlock == 4 {
			return true, nil, interact(validator.rpcPort).tx(operatorKey).mintStake(address, stakeDelta)
```

2020-09-10 06:08 UTC, Jason-Zhangxin-Chen commented on consensus/test/reward_distribution_test.go
> +			return nil
> Why do you start from block 2?

Could be removed now since the contract deployment is done in init phase.

2020-09-10 08:19 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +		}
> So now I can see what is going on more clearly in this test. I can see we are basically doing the same thing 3 times, once for validator, once for stakeholder and once for participant. Under the hood all those functions actually call the same function just with a different UserType parameter. Having these 3 separate functions is a bad design because it prevents us writing generic code that simply accepts the UserType parameter. We can see the effect of this bad design here because it is forcing us to write 3 times more code than we need to, in order to test it. It will have the same effect on people trying to integrate with the system, they will also end up duplicating things 3 times over to account for these 3 methods that do essentially the same thing. The same problem is repeated with the events emitted by these functions (having 3 different types of event for the three different user types).
> 
> So instead I suggest we make an AddUser fucntion in the autonity contract that accepts UserType as a parameter and remove the AddValidator, AddStakeholder and AddParticipant methods.
> 
> Then we can just test AddUser

Since this ticket is about the functionality e2e testing, let's create a new ticket in track with this proposal, is it fine for you?

2020-09-10 08:19 UTC, Jason-Zhangxin-Chen commented on consensus/test/reward_distribution_test.go
> +		}
> I think we can avoid using the statedb directly by using ethclient instead, and then here we can use the interactor, which saves us from having two different ways of achieving the same thing.
> 
> This approach may be much faster than calling via the RPC, but given that nodes wait a second between blocks and this tests specifies 30 blocks, I think the effect on the time taken to run this test of switching to the interactor would be imperceptible.

Resolved in my latest commit.

2020-09-10 08:20 UTC, Jason-Zhangxin-Chen commented on consensus/test/reward_distribution_test.go
> +			return nil
> > Why do you start from block 2?
> 
> Could be removed now since the contract deployment is done in init phase.



> Why do you start from block 2?

I remove it now since we have contract deployed at init block already.

2020-09-10 08:21 UTC, Jason-Zhangxin-Chen commented on consensus/test/reward_distribution_test.go
> +			}
> Instead of re-applying the txs to find the receipt lets use `ethclient.TransactionReceipt` to find the actual receipt for that block.

Resolved by my last commit.

2020-09-10 08:21 UTC, Jason-Zhangxin-Chen commented on consensus/test/reward_distribution_test.go
> +		}
> Rather than getting the parent and then finding the balance from it, I think it is clearer to use the `ethclient.BalanceAt`

Resolved by my last commit.

2020-09-10 08:21 UTC, Jason-Zhangxin-Chen commented on consensus/test/stake_management_test.go
> +			return true, nil, interact(validator.rpcPort).tx(operatorKey).mintStake(*validatorsList[0].Address, stakeDelta)
> 

Also resolved by my last commit.

2020-09-28 08:26 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +		}
Autonity User Management API was refined after the latest commit, please review them.

2020-09-28 08:28 UTC, Jason-Zhangxin-Chen commented
@yazzaoui @aneequesafdar @piersy , please review the AC User Management refine in the last commits, now in the testcases, we just make them leaner then before.

2020-09-30 12:17 UTC, yazzaoui approved these changes
Great!

2020-09-30 15:07 UTC, piersy commented on consensus/test/member_management_test.go
> +		}
i think it would be nice to refactor this to a function that checks a single user.

So something like, the following and we call it 3 times, once for each user.
```go
validateAddedUser(t, userPubKey, userType, userStake, whitelist currNetworkMetrics)
```

2020-09-30 15:09 UTC, piersy commented on consensus/test/member_management_test.go
> +		assert.Equal(t, b, stakeBalance.Uint64()*2, "stake total supply is not expected")
Can you document how exactly the stake supply is intended to change or link to documentation that explains how the stake supply should change. Without that reviewers cannot verify if this check is correct.

2020-09-30 15:21 UTC, piersy commented on consensus/test/member_management_test.go
> +		isMember, err := interact(validators["VA"].rpcPort).call(validators["VA"].lastBlock).checkMember(addressToRemove)
I'm a bit confused as to the meaning of member and the whitelist, are all members in the whitelist, and are all enodes in the whitelist members?

If they are two different ways of representing the same thing then I would say that we should decide on one standard way to check membership (above you check the whitelist) or we check that a user is both a member and in the whitelist to make sure they are in sync.

So now I am looking at the code in Autonity.sol I don't see a reason to maintain a separate whitelist, so would suggest  , removing the whitelist variable in the contract and rewriting getWhitelist to generate the whitelist from the users when called. Or even just to return the users and not bother with the whitelist at all and we can process the data on the go side.

2020-09-30 15:22 UTC, piersy commented on consensus/test/member_management_test.go
> +	// set up of hooks, which should be refactored since they share virtually the same code
Stray comment?
```suggestion
```

2020-09-30 15:34 UTC, piersy commented on consensus/test/member_management_test.go
> +	newValidatorNodeKey, err := keygenerator.Next()
We should probably remove keygenerator.

It takes slightly longer than `crypto.GenerateKey()` to run and is liable to cause issues if we ever generated more than 50 keys with it because it starts to reuse keys at that point.

2020-09-30 15:42 UTC, piersy commented on consensus/test/member_management_test.go
> +		curNetworkMetrics, err := interact(validators["VA"].rpcPort).call(validators["VA"].lastBlock).dumpEconomicsMetricData()
So looking at the method `dumpEconomicsMetricData` in `Autonity.sol` I'm wondering if we should keep it.

It is basically providing a re-representation of the information in users and adding min gas price  and stake supply into the mix. 

I think it would be much neater to just provide access to users and people can calculate what they need from that. If they want to know the min gas price they can make another call.

2020-09-30 15:54 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +	}
```suggestion
	require.NoError(t, err)
```

2020-09-30 15:58 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +		balanceBase, err := ec.BalanceAt(ctx, addr, parent.Number())
Couldn't we just use `block.NumberU64()-1` here instead of getting the parent?

2020-09-30 16:03 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +		return nil
This needs to be documented here or linked to documentation that explains the reward distribution mechanism, otherwise I cannot check if it is correct.

2020-09-30 16:12 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +		return nil
I think it would also be helpful to break this down into some smaller named functions, I'm finding it hard to read at the moment.

2020-09-30 16:20 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +	}
I don't see that we need all these different cases here. If this test is checking reward distribution then I would think it would be sufficient to check a network where no transactions are processed, so no reward is received and a network where some value transfer transactions are processed.

I don't see that we need to explicitly execute mint stake, redeem stake or transfer stake.

2020-09-30 16:40 UTC, piersy commented on consensus/test/stake_management_test.go
> +		}
What is going on here, this doesn't seem to make any sense to me

2020-09-30 16:47 UTC, piersy commented on consensus/test/stake_management_test.go
> +		validatorsList := validators["VA"].service.BlockChain().Config().AutonityContractConfig.GetValidatorUsers()
Rather than using `validatorsList` I think this could be made much simpler by setting up the sender and receiver at the beginning of the test.

E.g:
```go
sender := "VA"
receiver := "VB"
```
Then I think we can drop all use of the validatorsList

2020-09-30 17:12 UTC, piersy commented on consensus/test/stake_management_test.go
> +	stakeCheckerHook := func(t *testing.T, validators map[string]*testNode) {
I think we could make these checker hooks a lot simpler and improve the tests as well.

This hook checks for a delta after using the Abs function. That means we don't know if stake was added or taken away which is really critical.

Instead we can set some variables at the beginning of the test to make this easy.

```go
mintee := "VA"
initialStake := 100
mintAmount := 10
redeemAmount := 20
sendAmount := 30
```

Then we can have hooks like this, and we can make one per action. If we want to validate the total stake we can wrap that up in a function `validateTotalStake(t *testing.T, expectedTotal uint64)` and call that inside these hooks.
```go
mintCheckerHook := func(t *testing.T, validators map[string]*testNode) {
		m := validators[mintee]
		initStake, err := interact(m.rpcPort).call(3).getStake()
		require.NoError(t, err)
		assert.Equal(t, initialStake, initStake)

		endStake, err := interact(m.rpcPort).call(m.lastBlock).getStake()
		require.NoError(t, err)
		assert.Equal(t, initialStake+mintAmount, endStake)
```

2020-10-02 12:14 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +		assert.Equal(t, b, stakeBalance.Uint64()*2, "stake total supply is not expected")
> Can you document how exactly the stake supply is intended to change or link to documentation that explains how the stake supply should change. Without that reviewers cannot verify if this check is correct.

In autonity contract, there is total supply of stake token, system operator can manage it by adding stake for new user, or mint stake for exsited users too. I will comments on the testcase to let people have a better understanding.

2020-10-02 12:44 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +		isMember, err := interact(validators["VA"].rpcPort).call(validators["VA"].lastBlock).checkMember(addressToRemove)
> I'm a bit confused as to the meaning of member and the whitelist, are all members in the whitelist, and are all enodes in the whitelist members?
> 
> If they are two different ways of representing the same thing then I would say that we should decide on one standard way to check membership (above you check the whitelist) or we check that a user is both a member and in the whitelist to make sure they are in sync.
> 
> So now I am looking at the code in Autonity.sol I don't see a reason to maintain a separate whitelist, so would suggest , removing the whitelist variable in the contract and rewriting getWhitelist to generate the whitelist from the users when called. Or even just to return the users and not bother with the whitelist at all and we can process the data on the go side.

All the members(validator, stakeholder, participant)'s enode should present in the eNodeWhitelist which is used by the network permissioning for the time being, any changes of it should directly update the topology of the node ASAP on each new block,  keep it store in contract is fair enough.

2020-10-02 12:54 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +		curNetworkMetrics, err := interact(validators["VA"].rpcPort).call(validators["VA"].lastBlock).dumpEconomicsMetricData()
> So looking at the method `dumpEconomicsMetricData` in `Autonity.sol` I'm wondering if we should keep it.
> 
> It is basically providing a re-representation of the information in users and adding min gas price and stake supply into the mix.
> 
> I think it would be much neater to just provide access to users and people can calculate what they need from that. If they want to know the min gas price they can make another call.

Network Economic Metrics will be needed on each new block generation, we dump this information and store them into TSDB (prometheus or fluxDB) for BI, with these data, we can apply some tools to track and manage financial risks in the future.

2020-10-02 13:09 UTC, Jason-Zhangxin-Chen commented on consensus/test/reward_distribution_test.go
> +		return nil
> This needs to be documented here or linked to documentation that explains the reward distribution mechanism, otherwise I cannot check if it is correct.

In the ASC doc, we have so general specification about this part, like the block reward should be shared with fractions base on staking, but it does not specify the whole thing in such detail level. Here as you see in my comments: 
// check if balance is expected: base + reward + received - sent - gasUsed == bActual.
The actual balance of an account on each new block, should be calculated with:
balance on last block (base) + reward fractions on new block (reward) + received tokens of a TX on new block (received) - sent tokens of a TX on new block (sent) - gasUsed for issuing TX on new block (gasUsed)

2020-10-02 14:37 UTC, Jason-Zhangxin-Chen commented on consensus/test/reward_distribution_test.go
> +	}
> I don't see that we need all these different cases here. If this test is checking reward distribution then I would think it would be sufficient to check a network where no transactions are processed, so no reward is received and a network where some value transfer transactions are processed.
> 
> I don't see that we need to explicitly execute mint stake, redeem stake or transfer stake.

I don't think so, reward distribution base on staking should dynamically changes on the run time since system operator can manage staking state on the run time, and the simulation covers such normal scenario to make sure it work correctly.

2020-10-05 07:26 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +		}
> i think it would be nice to refactor this to a function that checks a single user.
> 
> So something like, the following and we call it 3 times, once for each user.
> 
> ```go
> validateAddedUser(t, userPubKey, userType, userStake, whitelist currNetworkMetrics)
> ```

Resolved at my latest commits.

2020-10-05 07:26 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +	newValidatorNodeKey, err := keygenerator.Next()
> We should probably remove keygenerator.
> 
> It takes slightly longer than `crypto.GenerateKey()` to run and is liable to cause issues if we ever generated more than 50 keys with it because it starts to reuse keys at that point.

Resolved at my latest commits.

2020-10-05 07:27 UTC, Jason-Zhangxin-Chen commented on consensus/test/reward_distribution_test.go
> +		balanceBase, err := ec.BalanceAt(ctx, addr, parent.Number())
> Couldn't we just use `block.NumberU64()-1` here instead of getting the parent?

Resolved at my latest commits.

2020-10-05 07:27 UTC, Jason-Zhangxin-Chen commented on consensus/test/reward_distribution_test.go
> +		return nil
> I think it would also be helpful to break this down into some smaller named functions, I'm finding it hard to read at the moment.
> 
> For example
> 
> ```go
> func sent(block *types.Block, addresss common.Address) uint64
> func received(block *types.Block, addresss common.Address) uint64
> func gasUsed((block *types.Block, addresss common.Address) uint64
> ```

Resolved at my latest commits.

2020-10-05 07:29 UTC, Jason-Zhangxin-Chen commented on consensus/test/stake_management_test.go
> +		}
> What is going on here, this doesn't seem to make any sense to me?

I refine this with in my latest commits, it was about to select a account as receiver of stake transacation.

2020-10-05 07:31 UTC, Jason-Zhangxin-Chen commented on consensus/test/stake_management_test.go
> +		validatorsList := validators["VA"].service.BlockChain().Config().AutonityContractConfig.GetValidatorUsers()
> Rather than using `validatorsList` I think this could be made much simpler by setting up the sender and receiver at the beginning of the test.
> 
> E.g:
> 
> ```go
> sender := "VA"
> receiver := "VB"
> ```
> 
> Then I think we can drop all use of the validatorsList

Not totally aggree but anyway the latest case should be easier to be understanded.

2020-10-05 07:31 UTC, Jason-Zhangxin-Chen commented on consensus/test/stake_management_test.go
> +	stakeCheckerHook := func(t *testing.T, validators map[string]*testNode) {
> I think we could make these checker hooks a lot simpler and improve the tests as well.
> 
> This hook checks for a delta after using the Abs function. That means we don't know if stake was added or taken away which is really critical.
> 
> Instead we can set some variables at the beginning of the test to make this easy.
> 
> ```go
> mintee := "VA"
> initialStake := 100
> mintAmount := 10
> redeemAmount := 20
> sendAmount := 30
> ```
> 
> Then we can have hooks like this, and we can make one per action. If we want to validate the total stake we can wrap that up in a function `validateTotalStake(t *testing.T, expectedTotal uint64)` and call that inside these hooks.
> 
> ```go
> mintCheckerHook := func(t *testing.T, validators map[string]*testNode) {
> 	m := validators[mintee]
> 	initStake, err := interact(m.rpcPort).call(3).getStake()
> 	require.NoError(t, err)
> 	assert.Equal(t, initialStake, initStake)
> 
> 	endStake, err := interact(m.rpcPort).call(m.lastBlock).getStake()
> 	require.NoError(t, err)
> 	assert.Equal(t, initialStake+mintAmount, endStake)
> }
> ```

Resolved at my latest commits.

2020-10-06 10:01 UTC, piersy commented on consensus/test/member_management_test.go
> +		isMember, err := interact(validators["VA"].rpcPort).call(validators["VA"].lastBlock).checkMember(addressToRemove)
> All the members(validator, stakeholder, participant)'s enode should present in the eNodeWhitelist

In this case I don't see a reason to duplicate the information about who is in the whitelist (I.e in the whitelist and also in users) but we could consider it an issue that is outside of the scope of this PR. But we should at least be consistent about how we check for users existing. In the `addUserCheckerHook` you check that the user is in both the whitelist and that `checkMember` returns true.

So we should be consistent and for this check verify that the user is not a member and not in the whitlist.

I suggest creating a function to encapsulate this.

```go
func isParticipant(port int, height uint64, adress common.Address, eNode string) bool {
	whiteList, err := interact(port).call(height).getWhitelist()
	require.NoError(t, err)
	var inWhitelist bool
	for _, en := range whitelist {
		if en == eNode {
			inWhitelist = true
			break		
		}
	}
	isMember, err := interact(port).call(height).checkMember(address)
	require.NoError(t, err)
	assert.Equal(t, isMember, inWhitelist) // If these are not equal then we have inconsistent contract state
	return isMember && inWhitelist
}
```

2020-10-06 10:35 UTC, piersy commented on consensus/test/member_management_test.go
> +		curNetworkMetrics, err := interact(validators["VA"].rpcPort).call(validators["VA"].lastBlock).dumpEconomicsMetricData()
So this is out of scope of this PR But my point is that, the information in dumpEcenomic metrics data can be retrieved by getting the users and min gas price. We don't need a special function in the contract to merge the data, we can do it in golang which is much easier to work with.

2020-10-06 11:49 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +	}
So really the problem I see with this test is that it is not checking that mint stake, redeem stake or transfer stake are having any effect.

Because `calculateBalanceFactors` only takes into account the receipts it is not able to verify whether mint stake, redeem stake or transfer stake are working properly. This means that this test would pass regardless of how mint stake, redeem stake and transfer stake are working. E.g it would pass if they all had no effect, it would pass if mint stake removed stake from a user and it would pass if send stake multiplied the stake of the sender by 2 and did nothing to the receiver.

So having these explicit cases for mint stake, redeem stake and transfer stake, don't actually provide any more assurance that the system is working beyond a test with fixed staking. So we should remove them, or verify that they are working as expected. Given that we already do check the functionality of these operations in `TestStakeManagement` we shouldn't duplicate that work here and therefore we should just remove these cases.

2020-10-06 12:14 UTC, piersy commented on consensus/test/stake_management_test.go
> +		validatorsList := validators["VA"].service.BlockChain().Config().AutonityContractConfig.GetValidatorUsers()
Could you elaborate on why you don't agree?

What I'm suggesting is that this:
```go
	sender := "VA"
	receiver := "VB"

...

	receiverInitBalance, err := getBalance(port, 3, validators[reciever].Address)
```
Is simpler than this:
```go
	pickReceiver := func(validator *testNode) common.Address {
		senderAddress := crypto.PubkeyToAddress(validator.privateKey.PublicKey)
		validatorsList := validator.service.BlockChain().Config().AutonityContractConfig.GetValidatorUsers()
		toIndex := 0
		if senderAddress == *validatorsList[toIndex].Address {
			toIndex = 1
		}
		return *validatorsList[toIndex].Address
	}

...

	receiverAddr := pickReceiver(validators["VA"])
	receiverInitBalance, err := getBalance(port, 3, receiverAddr)
```

2020-10-06 12:20 UTC, piersy commented on consensus/test/stake_management_test.go
> +	stakeCheckerHook := func(t *testing.T, validators map[string]*testNode) {
I can see you are still making use of the `Abs` function in calculating the delta, i think this means that the test is not validating if stake is added or removed.

2020-10-07 07:53 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +		isMember, err := interact(validators["VA"].rpcPort).call(validators["VA"].lastBlock).checkMember(addressToRemove)
> > All the members(validator, stakeholder, participant)'s enode should present in the eNodeWhitelist
> 
> In this case I don't see a reason to duplicate the information about who is in the whitelist (I.e in the whitelist and also in users) but we could consider it an issue that is outside of the scope of this PR. But we should at least be consistent about how we check for users existing. In the `addUserCheckerHook` you check that the user is in both the whitelist and that `checkMember` returns true.
> 
> So we should be consistent and for this check verify that the user is not a member and not in the whitlist.
> 
> I suggest creating a function to encapsulate this.
> 
> ```go
> func isParticipant(port int, height uint64, adress common.Address, eNode string) bool {
> 	whiteList, err := interact(port).call(height).getWhitelist()
> 	require.NoError(t, err)
> 	var inWhitelist bool
> 	for _, en := range whitelist {
> 		if en == eNode {
> 			inWhitelist = true
> 			break		
> 		}
> 	}
> 	isMember, err := interact(port).call(height).checkMember(address)
> 	require.NoError(t, err)
> 	assert.Equal(t, isMember, inWhitelist) // If these are not equal then we have inconsistent contract state
> 	return isMember && inWhitelist
> }
> ```

Resolved in my last commit by adding this isParticipant function.

2020-10-07 07:58 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +		curNetworkMetrics, err := interact(validators["VA"].rpcPort).call(validators["VA"].lastBlock).dumpEconomicsMetricData()
> So this is out of scope of this PR But my point is that, the information in dumpEcenomic metrics data can be retrieved by getting the users and min gas price. We don't need a special function in the contract to merge the data, we can do it in golang which is much easier to work with.

Collecting the economic metrics happens on each new state (new block) for per user, to save the performance cost of lifting a EVM again and again for different user, we decided to aggregate data in contract side, then dump once right after a block is finalized.

2020-10-07 08:07 UTC, Jason-Zhangxin-Chen commented on consensus/test/reward_distribution_test.go
> +	}
> So really the problem I see with this test is that it is not checking that mint stake, redeem stake or transfer stake are having any effect.
> 
> Because `calculateBalanceFactors` only takes into account the receipts it is not able to verify whether mint stake, redeem stake or transfer stake are working properly. This means that this test would pass regardless of how mint stake, redeem stake and transfer stake are working. E.g it would pass if they all had no effect, it would pass if mint stake removed stake from a user and it would pass if send stake multiplied the stake of the sender by 2 and did nothing to the receiver.
> 
> So having these explicit cases for mint stake, redeem stake and transfer stake, doesn't actually provide any more assurance that the system is working beyond a test with fixed staking. So we should remove them, or verify that they are working as expected. Given that we already do check the functionality of these operations in `TestStakeManagement` we shouldn't duplicate that work here and therefore we should just remove these cases.

The purpose of MintStake, RedeemStake and TransferStake are simulating the changes of the stake in the system on the run time, and reward distribution should work correctly during this period as the fix staking scenario. I think they are valuable.

2020-10-07 08:28 UTC, Jason-Zhangxin-Chen commented on consensus/test/stake_management_test.go
> +		validatorsList := validators["VA"].service.BlockChain().Config().AutonityContractConfig.GetValidatorUsers()
> Could you elaborate on why you don't agree?
> 
> What I'm suggesting is that this:
> 
> ```go
> 	sender := "VA"
> 	receiver := "VB"
> 
> ...
> 
> 	receiverInitBalance, err := getBalance(port, 3, validators[reciever].Address)
> ```
> 
> Is simpler than this:
> 
> ```go
> 	pickReceiver := func(validator *testNode) common.Address {
> 		senderAddress := crypto.PubkeyToAddress(validator.privateKey.PublicKey)
> 		validatorsList := validator.service.BlockChain().Config().AutonityContractConfig.GetValidatorUsers()
> 		toIndex := 0
> 		if senderAddress == *validatorsList[toIndex].Address {
> 			toIndex = 1
> 		}
> 		return *validatorsList[toIndex].Address
> 	}
> 
> ...
> 
> 	receiverAddr := pickReceiver(validators["VA"])
> 	receiverInitBalance, err := getBalance(port, 3, receiverAddr)
> ```

In the current test framework, in the context of sendTransactionHook, there is no way to get the global validators map.

2020-10-07 10:56 UTC, piersy commented on consensus/test/member_management_test.go
> +		curNetworkMetrics, err := interact(validators["VA"].rpcPort).call(validators["VA"].lastBlock).dumpEconomicsMetricData()
So I would consider that a premature optimisation. We don't have any performance analysis of the system so we don't know if this would improve performance, it might degrade performance. But it definitely complicates the contract which makes more work for us.

2020-10-07 11:39 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +  The TX issuing and reward checking work flow are keep running during each new block is mined.
I've provided a re-wording of this comment. As it stood the comment included some unnecessary information such as "THe work flow is base on the local e2e test framework's main flow" which would be true for all tests using this framework. It also failed to define what reward was in the equation provided.

```suggestion
This test checks that at each block rewards are distributed correctly. 

We check four different scenarios.

* Validators' stake remains constant
* A validator has stake minted (added) each block.
* A validator has stake redeemed (removed) each block.
* A validator sends stake to another validator each block.

The reward distribution model that we are following is defined here - https://core.clearmatics.net/ASC_core_v3.html#with-no-proposer-bonus-fees.

It can be summarised as each validator is rewarded with a portion of the total fees for a block that is proportional to the amount of stake they own. The total fees for a block is the sum of the fees of the transactions where a transaction fee is the gas used multiplied by the gas price.

For each scenario after each block we check that the balance of each validator is as expected, taking into account its stake at that block, any value that has been sent or received at that block and any gas used in that block.
```

2020-10-07 12:00 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +	calculateBalanceFactors := func(block *types.Block, node *testNode) (*big.Int, *big.Int, *big.Int, *big.Int, error) {
This function is a bit confusing because it mixes its return parameters so that 3 are values specific to the node and then one of them is global (the block reward). I think it would be clearer to be consistent here and either return global (block level) values or node specific values but not  a mix of the two.

Looking at the comment it implies that the block reward is specific to the node when it is not 
>blockReward on per block for node

Which I think highlights how this function easily leads to confusion.

2020-10-07 12:02 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +	}
Ok lets keep them.

2020-10-07 12:06 UTC, piersy commented on consensus/test/member_management_test.go
> +	addUserHook := func(validator *testNode, _ common.Address, _ common.Address) (bool, *types.Transaction, error) { //nolint
```suggestion
	addUsersHook := func(validator *testNode, _ common.Address, _ common.Address) (bool, *types.Transaction, error) { //nolint
```

2020-10-07 12:06 UTC, piersy commented on consensus/test/member_management_test.go
> +	}
I think we could drop this function, its not adding anything.

2020-10-07 12:09 UTC, piersy commented on consensus/test/member_management_test.go
> +	addUserCheckerHook := func(t *testing.T, validators map[string]*testNode) {
```suggestion
	addUsersCheckerHook := func(t *testing.T, validators map[string]*testNode) {
```

2020-10-07 12:11 UTC, piersy commented on consensus/test/member_management_test.go
> +			err := addUser(operatorKey, validator.rpcPort, newValidatorPubKey, validatorStake, newValidatorENode, uint8(2))
It would be nice to assign the roles to variables, so we don't have these mystery values being duplicated in the test.

for example
```suggestion
			err := addUser(operatorKey, validator.rpcPort, newValidatorPubKey, validatorStake, newValidatorENode, validatorRole)
```

2020-10-07 12:14 UTC, piersy commented on consensus/test/stake_management_test.go
> +		return interact(port).call(blockNum).getAccountStake(address)
I think we can remove this function now.

2020-10-07 12:14 UTC, piersy commented on consensus/test/stake_management_test.go
> +	}
I think we can remove this function now.

2020-10-07 12:16 UTC, piersy commented on consensus/test/test_helpers_test.go
> +		stake := uint64(InitStake)
I don't see a reason to define this as global if its only going to be used in one place

2020-10-07 12:19 UTC, piersy commented on consensus/test/stake_management_test.go
> +		validatorsList := validators["VA"].service.BlockChain().Config().AutonityContractConfig.GetValidatorUsers()
Ahh, I hadn't realised. Its interesting to see how this testing framework makes simple things so complicated.

2020-10-07 12:23 UTC, piersy requested changes
Hi @Jason-Zhangxin-Chen, hopefully the last few comments from me!

2020-10-07 13:48 UTC, Jason-Zhangxin-Chen commented on consensus/test/reward_distribution_test.go
> +	calculateBalanceFactors := func(block *types.Block, node *testNode) (*big.Int, *big.Int, *big.Int, *big.Int, error) {
> This function is a bit confusing because it mixes its return parameters so that 3 are values specific to the node and then one of them is global (the block reward). I think it would be clearer to be consistent here and either return global (block level) values or node specific values but not a mix of the two.
> 
> Looking at the comment it implies that the block reward is specific to the node when it is not
> 
> > blockReward on per block for node
> 
> Which I think highlights how the approach of mixing global and node specific return values easily leads to confusion.

Since we check reward distribution right after each new block's generation, and each node should perform such check base on its local ledger, so the calculater function count those meta data: sentTokens, receivedTokens, gasUsed, and blockReward for the next checkers. I update the comments some how to make it easier to be understand, hope it does help to reslove the confusion.

2020-10-07 13:56 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +	addUserHook := func(validator *testNode, _ common.Address, _ common.Address) (bool, *types.Transaction, error) { //nolint
Resolved.

2020-10-07 14:02 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +	}
> I think we could drop this function, its not adding anything.

Resolved.

2020-10-07 14:04 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +	addUserCheckerHook := func(t *testing.T, validators map[string]*testNode) {
> 

Resolved.

2020-10-07 14:09 UTC, Jason-Zhangxin-Chen commented on consensus/test/stake_management_test.go
> +	}
> I think we can remove this function now.

Resolved.

2020-10-07 14:14 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +			err := addUser(operatorKey, validator.rpcPort, newValidatorPubKey, validatorStake, newValidatorENode, uint8(2))
> It would be nice to assign the roles to variables, so we don't have these mystery values being duplicated in the test.
> 
> for example

Resloved.

2020-10-07 14:18 UTC, Jason-Zhangxin-Chen commented on consensus/test/test_helpers_test.go
> +		stake := uint64(InitStake)
> I don't see a reason to define this as global if its only going to be used in one place

Resolved too.

2020-10-07 14:29 UTC, Jason-Zhangxin-Chen commented
> Hi @Jason-Zhangxin-Chen, hopefully the last few comments from me!

Thank you, Piers. 
Please review my refines base on your last comments.

2020-10-14 09:54 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +	calculateBalanceFactors := func(block *types.Block, node *testNode) (*big.Int, *big.Int, *big.Int, *big.Int, error) {
You have just flipped the problem around

Now the docs say
>// calculate sentTokens, receivedTokens, gasUsed, blockReward on per block.

But this is not calculating the per block sentTokens, receivedTokens and gasUsed its calculating them for the specific node in that block.

I will add a multiline suggestion.

2020-10-14 10:02 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +	}
This makes the return parameters consistent for this function, since they now all represent values from the node's point of view.

Obviously you would now need to remove the call to calculateRewardFraction at line 140.

```suggestion
	// calculate sentTokens, receivedTokens, gasUsed and blockReward for the given node in the given block.
	calculateRewardMetaPerBlock := func(block *types.Block, node *testNode) (*big.Int, *big.Int, *big.Int, *big.Int, error) {
		client, err := node.node.Attach()
		if err != nil {
			return nil, nil, nil, nil, err
		}
		defer client.Close()
		ec := ethclient.NewClient(client)
		ctx, cancel := context.WithTimeout(context.Background(), 1000*time.Millisecond)
		defer cancel()
		// calculate sent, gasUsed, receive amount and reward on the block.
		sentAmount := new(big.Int)
		receivedAmount := new(big.Int)
		usedGas := new(big.Int)
		blockReward := new(big.Int)
		for _, tx := range block.Transactions() {
			receipt, err := ec.TransactionReceipt(ctx, tx.Hash())
			if err != nil {
				return nil, nil, nil, nil, err
			}

			// count reward on this block.
			txGasConsumed := new(big.Int).Mul(tx.GasPrice(), new(big.Int).SetUint64(receipt.GasUsed))
			blockReward.Add(blockReward, txGasConsumed)

			// count received amount on this block.
			if *tx.To() == crypto.PubkeyToAddress(node.privateKey.PublicKey) {
				receivedAmount.Add(receivedAmount, tx.Value())
			}

			// count sent and gasUsed amount on this block.
			node.transactionsMu.Lock()
			if _, ok := node.transactions[tx.Hash()]; ok {
				sentAmount.Add(sentAmount, tx.Value())
				usedGas.Add(usedGas, txGasConsumed)
			}
			node.transactionsMu.Unlock()
		}
		return sentAmount, receivedAmount, usedGas, calculateRewardFraction(block.NumberU64(), blockReward, testNode.rpcPort, crypto.PubkeyToAddress(testNode.privateKey.PublicKey)
	}
```

2020-10-14 10:18 UTC, Jason-Zhangxin-Chen commented on consensus/test/reward_distribution_test.go
> +	calculateBalanceFactors := func(block *types.Block, node *testNode) (*big.Int, *big.Int, *big.Int, *big.Int, error) {
> You have just flipped the problem around
> 
> Now the docs say
> 
> > // calculate sentTokens, receivedTokens, gasUsed, blockReward on per block.
> 
> But this is not calculating the per block sentTokens, receivedTokens and gasUsed its calculating them for the specific node in that block.
> 
> I will add a multiline suggestion.

The code here works correctly since we check this distribution works from each node's ledger. Do you have some better suggestion on the comments of this part, please submit a suggestion on this finding. Thank you, Piers.

2020-10-14 11:31 UTC, piersy commented on consensus/test/reward_distribution_test.go
> +	calculateBalanceFactors := func(block *types.Block, node *testNode) (*big.Int, *big.Int, *big.Int, *big.Int, error) {
Hi @Jason-Zhangxin-Chen,

I have made a PR for this suggestion, please find it here #702

2020-10-14 11:35 UTC, piersy commented on consensus/test/member_management_test.go
> +			numBlocks:     30,
I just ran the tests and they took quite a while on my local machine, is there a reason we set the number of blocks to 30 when the actions we are testing are taking place in block 4?

And the same question for all the other tests too.

2020-10-15 05:09 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +			numBlocks:     30,
> I just ran the tests and they took quite a while on my local machine, is there a reason we set the number of blocks to 30 when the actions we are testing are taking place in block 4?
> 
> And the same question for all the other tests too.

I set them into 10 blocks now.

2020-10-15 05:16 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +			numBlocks:     30,
> I just ran the tests and they took quite a while on my local machine, is there a reason we set the number of blocks to 30 when the actions we are testing are taking place in block 4?
> 
> And the same question for all the other tests too.

It all about to wait for the TXs to be mined by miner.

2020-10-16 14:39 UTC, piersy commented on consensus/test/member_management_test.go
> +			numBlocks:     30,
Could you add a comment into the test to explain this?

2020-10-16 15:10 UTC, Jason-Zhangxin-Chen commented on consensus/test/member_management_test.go
> +			numBlocks:     30,
> Could you add a comment into the tests to explain this?

Add comments on the setting of relative bigger numBlocks for the cases in my last commit.

2020-10-19 08:27 UTC, piersy approved these changes
Happy days, I'm approving! :stuck_out_tongue:

2020-10-19 08:41 UTC, merged

2020-10-19 08:42 UTC, Jason-Zhangxin-Chen commented
This is a marathon run, finally get to the finish line. Thank you, Piers.