Autonity rpc
clearmatics/autonity pull request #691
Opened 2020-09-28 10:33 UTC by aneequesafdar

2020-10-12 04:30 UTC, Jason-Zhangxin-Chen approved these changes
LGTM. Just one comment: to add a local e2e testcase which calls one of the API, to make sure that no one will break this feature accidently in the future.

2020-10-20 12:04 UTC, yazzaoui commented on eth/backend.go
> +			Namespace: "autonityContract",
```suggestion
			Namespace: "aut",
```

2020-10-29 15:46 UTC, piersy requested changes
This is really your comment @aneequesafdar, we should have some consistency in the naming. so either we prefix all calls with 'get' or we remove the 'get' prefix. Looking at the ethereum rpcs it looks like having the 'get' prefix is the standard approach so I'd suggest we add that to them all.

2020-10-29 15:50 UTC, aneequesafdar commented
Which get are you talking about, @piersy ?

2020-10-29 15:57 UTC, piersy commented on accounts/abi/argument.go
> +// isTuple returns true for non-atomic constructs, like (uint,uint) or uint[]
This documentation looks out of place, this function should have a godoc comment.

2020-10-29 15:59 UTC, piersy commented on contracts/autonity/autonity.go
>  func (ac *Contract) GetContractABI() string {
I'd suggest renaming this as `StringABI `to distinguish it from `ABI`

2020-10-29 16:00 UTC, piersy commented on contracts/autonity/calls.go
> +func (ac *Contract) AutonityContractCallUnpackIntoMap(statedb *state.StateDB, header *types.Header, function string, result map[string]interface{}, args ...interface{}) error {
This needs documentation.

2020-10-29 16:01 UTC, piersy commented on contracts/autonity/autonity.go
> +func (ac *Contract) ABI() *abi.ABI {
This needs documentation.

2020-10-29 16:01 UTC, piersy commented on contracts/autonity/calls.go
> +func (ac *Contract) callContractFunc(statedb *state.StateDB, header *types.Header, function string, args []interface{}) ([]byte, error) {
This needs documentation.

2020-10-29 16:01 UTC, piersy commented on eth/api.go
> +
This whole file needs documentation.

2020-10-29 16:02 UTC, piersy commented on rpc/service.go
> +// registerCallbacks register new callbacks is the receiver implement DynamicCallbacks.
This needs some better documentation

2020-10-29 16:04 UTC, piersy commented on rpc/service.go
> +// DynamicCallbacks is used for receivers with dynamic API's method to retrieve.
I think we need to expand this comment to explain what a receiver is and explain more what a dynamic api is.

2020-10-30 16:48 UTC, aneequesafdar commented on contracts/autonity/autonity.go
> +func (ac *Contract) ABI() *abi.ABI {
Seems to be self-explanatory but I have added a comment.

2020-10-30 16:50 UTC, aneequesafdar commented on eth/api.go
> +
We didn't write the whole file so I can't document the whole file

2020-10-30 18:08 UTC, aneequesafdar commented on accounts/abi/argument.go
> +// isTuple returns true for non-atomic constructs, like (uint,uint) or uint[]
Please look at the latest changes

2020-10-30 18:08 UTC, aneequesafdar commented on contracts/autonity/autonity.go
>  func (ac *Contract) GetContractABI() string {
Please look at the latest changes

2020-10-30 18:09 UTC, aneequesafdar commented on contracts/autonity/calls.go
> +func (ac *Contract) AutonityContractCallUnpackIntoMap(statedb *state.StateDB, header *types.Header, function string, result map[string]interface{}, args ...interface{}) error {
Please look at the latest changes

2020-10-30 18:09 UTC, aneequesafdar commented on contracts/autonity/autonity.go
> +func (ac *Contract) ABI() *abi.ABI {
Please look at the latest changes

2020-10-30 18:09 UTC, aneequesafdar commented on contracts/autonity/calls.go
> +func (ac *Contract) callContractFunc(statedb *state.StateDB, header *types.Header, function string, args []interface{}) ([]byte, error) {
Please look at the latest changes

2020-10-30 18:09 UTC, aneequesafdar commented on eth/api.go
> +
Please look at the latest changes for the comments for our work

2020-10-30 18:10 UTC, aneequesafdar commented on rpc/service.go
> +// registerCallbacks register new callbacks is the receiver implement DynamicCallbacks.
Please look at the latest changes

2020-10-30 18:10 UTC, aneequesafdar commented on rpc/service.go
> +// DynamicCallbacks is used for receivers with dynamic API's method to retrieve.
Please look at the latest changes

2020-10-30 18:11 UTC, piersy commented on accounts/abi/argument.go
> +// Types returns the list of underlying []reflect.Type for Arguments
```suggestion
// Types returns the list of underlying []reflect.Type for Arguments.
```

The first sentence of godoc is formatted differently so the full stop is important.

2020-10-30 18:15 UTC, piersy commented on contracts/autonity/calls.go
> +// The caller need to provide the object into which the results need to be returned.
```suggestion
// The caller needs to provide the object into which the results need to be returned.
```

2020-10-30 18:15 UTC, piersy commented on contracts/autonity/calls.go
> +// contract function along with the arguments, in any, and return the result in a map[string]interface{} object.
```suggestion
// contract function along with the arguments, if any, and return the result in a map[string]interface{} object.
```

2020-10-30 19:19 UTC, piersy commented
> Which "get" are you talking about, @piersy?
> 
> If you are referring to the names of the rpc calls, those are all dynamically generated from the names of the functions present in the autonity contract. Ideally you would want the names of the functions to remain the same as the names of the functions in the contract so that people know that calling the contract via web3 or transaction or through this rpc will all return the same result.

I agree that we want the methods to match the names of the functions, but I think before we expose these as an API we should get our functions named in a consistent way. If we put this out there as it is and people start building on it we'll either be stuck with the current function names or we could change the function names without changing the rpc names and then we'd be in the situation where the names differ.

2020-10-30 19:22 UTC, piersy requested changes
I don't see any tests for this, we should have them.

2020-10-30 19:25 UTC, aneequesafdar commented
>I agree that we want the methods to match the names of the functions, but I think before we expose these as an API we should get our functions named in a consistent way. If we put this out there as it is and people start building on it we'll either be stuck with the current function names or we could change the function names without changing the rpc names and then we'd be in the situation where the names differ.

But that can be said for the autonity contract as well and the transactions people are sending will make it difficult to change the function name. So I don't see this as an issue for this pr as they are dynamically generated and the rpc will change when the autonity contract is changed.

2020-10-30 19:39 UTC, piersy commented
> This PR is just describing the mechanism for creating the rpc, so once the function names of auotnity contract are finalised it will be automatically reflected. The function names that I mention in the description are based on the current autonity contract, if you add another abi in genesis, they will be different.
> 
> For me rpc name will always be from autonity contract and it should take precedence because that is what the API is giving access to.

If we make it clear to everyone that these rpcs are not stable and that people cannot rely on the API from release to release then I think this is not a problem.

2020-10-30 20:14 UTC, piersy commented on eth/api.go
> +	eth   *Ethereum
I don't think this is used. And if that is the case we should be constructing `AutonityContractAPI` with an instance of `Blockchain` since that is the smallest dependency that will satisfy `AutonityContractAPI's` requirements.

2020-10-30 20:16 UTC, piersy commented on contracts/autonity/calls.go
> +func (ac *Contract) AutonityContractCallUnpackIntoMap(statedb *state.StateDB, header *types.Header, function string, result map[string]interface{}, args ...interface{}) error {
The documentation says it returns a map but it just returns an error

2020-10-30 20:37 UTC, piersy commented on eth/api.go
> +}
I think this should be in the autonity package. It's definitely not part of the eth api

2020-10-30 20:53 UTC, piersy commented on rpc/service.go
> +func newDynamicCallbacks(callbacks map[string]*callback, receiver reflect.Value, methods map[string]reflect.Value) {
Why not have this return the callbacks, the name is also confusing because you would expect it to make an instance of DynamicCallbacks.

2020-10-30 20:56 UTC, piersy commented on contracts/autonity/calls.go
> +// callContractFunc create creaties an evm object required to call the autonity contract function and returns the result
```suggestion
// callContractFunc create creates an evm object required to call the autonity contract function and returns the result
```

2020-10-30 21:08 UTC, piersy commented on rpc/service.go
> +	Calls() map[string]reflect.Value
```suggestion
	MethodSignatures() map[string]reflect.Value
```

2020-10-30 21:11 UTC, piersy commented on rpc/service.go
> +	// Call should return a map of function names to function signatures, which will be used to create callbacks.
```suggestion
	// Call should return a map of function names to functions, which will be used to create callbacks.
```

2020-10-30 21:13 UTC, piersy commented on rpc/service.go
> +type DynamicCallbacks interface {
I'd probably just call this `Methods` there's nothing intrinsically 'dynamic' about this interface it just provides a map of methods.

Actually its not clear if this is returning methods or functions?

2020-11-03 14:20 UTC, piersy commented
@yazzaoui @Jason-Zhangxin-Chen @aneequesafdar  I'm not sure what to do about this PR.

It seems that deep inside the rpc mechanism there is an assumption that pointer arguments to a method are optional. This allows rpc calls to progress when they have not been called with the corresponding pointer arguments. It looks like the existing eth API methods are written to avoid the use of pointers fro required arguments. In the case of getProposer its arguments are uint256 which transalte to *big.Int on the go side. This allows the call to continue when neither height or round is provided, resulting in the rpc handler crashing.

I've tried removing the check for optional pointer parameters, but this resulted in lots of other stuff breaking.

https://github.com/clearmatics/autonity/blob/25e42b420098cf4d28a1dcb762fe56c7794699ee/rpc/json.go#L303-L305

2020-11-03 16:03 UTC, yazzaoui commented
@piersy Please check my latest commit.

2020-11-04 10:38 UTC, piersy commented on eth/api.go
> +}
Now that I have tried moving this, I can say that it can't go in the autonity package because of the circular dependencies we would encounter.

2020-11-04 13:47 UTC, piersy approved these changes

2020-11-04 14:43 UTC, yazzaoui commented on eth/api.go
> -					if len(res) == 1 {
Can we have this back? Found it would make the APIs easier to use.

2020-11-04 16:01 UTC, piersy commented on eth/api.go
> -					if len(res) == 1 {
I've restored previous functionality, but in a simpler way

2020-11-04 17:53 UTC, yazzaoui commented on eth/api.go
> +					v := reflect.ValueOf(result)
Wouldn't
```golang
if len(result) == 1 {
  return makereturn(result[0], err)
}
```
be enough ?

2020-11-04 17:53 UTC, yazzaoui approved these changes
LGTM

2020-11-05 10:30 UTC, piersy commented on eth/api.go
> +					v := reflect.ValueOf(result)
Yeah, it would :) I thought I was dealing with a `reflect.Value`

2020-11-05 11:26 UTC, Jason-Zhangxin-Chen approved these changes
LGTM

2020-11-06 14:15 UTC, merged