Merge go-ethereum 1.9.23
clearmatics/autonity pull request #703
Opened 2020-10-19 16:04 UTC by yazzaoui

closes #694 #693

2020-10-21 12:38 UTC, aneequesafdar commented on cmd/autonity/chaincmd.go
> -	}
I am not sure why do you want to always dump the default genesis. Is there a specific reason?

2020-10-21 12:50 UTC, aneequesafdar commented on core/rawdb/database.go
> -			bloomBitsSize += size
Could you give some context for this change?

2020-10-21 13:03 UTC, aneequesafdar commented on metrics/registry.go
> -	}
similar to the previous comment, can you please give some context to why we want to remove this function?

2020-10-21 14:12 UTC, aneequesafdar commented on contracts/autonity/autonity.go
> +	if err := ABI.UnpackIntoInterface(&v, "dumpEconomicsMetricData", ret); err != nil {
the type of `v` was not changed so why are you using `UnpackIntoInterface`, based on the comment it is meant to be called when we are not passing a type which conforms to the result, which is not the case here

2020-10-21 14:16 UTC, aneequesafdar commented on ethclient/ethclient_test.go
> +	gblock, _ := genesis.ToBlock(db)
we shouldn't ignore errors

2020-10-22 10:20 UTC, piersy requested changes
This is not compiling, so that needs to be resolved before we can even consider this PR

2020-10-22 10:39 UTC, piersy commented on p2p/server.go
> +}
Can we move this back?

2020-10-22 10:43 UTC, piersy commented on consensus/consensus.go
> +	Seal(chain ChainReader, block *types.Block, results chan<- *types.Block, stop <-chan struct{}) error
This seems like a dangerous change. If the go-ethereum team start passing objects here that are only ChainHeaderReaders we could get stuck.

2020-10-22 10:43 UTC, piersy commented on cmd/autonity/chaincmd.go
> -	}
This definitely looks wrong.

2020-10-22 10:52 UTC, piersy commented on consensus/test/test_helpers_test.go
> +		panic(err)
Instead of panicking use `require.NoError`

2020-10-22 10:52 UTC, piersy commented on consensus/test/testcase_test.go
> +	log.Root().SetHandler(log.LvlFilterHandler(log.LvlDebug, log.StreamHandler(os.Stderr, log.TerminalFormat(true))))
Do we really want this change?

2020-10-22 10:55 UTC, piersy commented on miner/worker.go
> +		err := pos.Start(context.Background())
Shouldn't we be using a cancellable context here?

2020-10-22 11:05 UTC, piersy commented on metrics/meter.go
> +	ma.doneCh <- struct{}{}
You don't need to lock here, channel communication is synchronised

2020-10-22 11:07 UTC, piersy commented on metrics/registry.go
> +	}
This should be encapsulated in `arbiter.stopTicker`

2020-10-22 15:22 UTC, yazzaoui commented on metrics/registry.go
> -	}
They made some changes in the metrics package, I needed to test if they've fixed the leak because we did actually introduce this method with https://github.com/clearmatics/autonity/pull/407 .
Ultimately the leak was still present so I reintroduced this fix.

2020-10-22 15:24 UTC, yazzaoui commented on contracts/autonity/autonity.go
> +	if err := ABI.UnpackIntoInterface(&v, "dumpEconomicsMetricData", ret); err != nil {
They've changed the signature of `abi.Unpack`, `UnpackIntoInterface` is the old `Unpack` .

2020-10-22 15:28 UTC, yazzaoui commented on ethclient/ethclient_test.go
> +	gblock, _ := genesis.ToBlock(db)
It would have panicked but I'll make it more explicit.

2020-10-22 15:33 UTC, yazzaoui commented on p2p/server.go
> +}
It's not that straightforward, would entail changes that I don't think are in the scope of this PR. 
I'm happy to keep it for later, I'll create a ticket once this gets merged.

2020-10-22 16:03 UTC, yazzaoui commented on miner/worker.go
> +		err := pos.Start(context.Background())
That was our old code, I didn't change that.

2020-10-22 16:15 UTC, yazzaoui commented on cmd/autonity/chaincmd.go
> -	}
I'll remove it then, it was previously calling `utils.Makegensis` which was returning some default hardcoded genesis depending on the CLI flags, see https://github.com/ethereum/go-ethereum/blob/fb2c79df1995b4e8dfe79f9c75464d29d23aaaf4/cmd/utils/flags.go#L1785-L1800

2020-10-22 16:19 UTC, yazzaoui commented on core/rawdb/database.go
> -			bloomBitsSize += size
It's a merge conflict that I've missed in my first pass see https://github.com/ethereum/go-ethereum/blob/fb2c79df1995b4e8dfe79f9c75464d29d23aaaf4/core/rawdb/database.go#L348-L349

2020-10-22 16:20 UTC, yazzaoui commented on metrics/meter.go
> +	ma.doneCh <- struct{}{}
See https://github.com/clearmatics/autonity/pull/703#discussion_r510250744

2020-10-22 16:20 UTC, yazzaoui commented on metrics/registry.go
> +	}
See https://github.com/clearmatics/autonity/pull/703#discussion_r510250744

2020-10-23 09:07 UTC, piersy commented on metrics/meter.go
> +	ma.doneCh <- struct{}{}
https://github.com/clearmatics/autonity/pull/703#discussion_r510250744 did not help me understand

2020-10-26 15:24 UTC, piersy commented on p2p/server.go
> +}
Why did you move this in the first place?

2020-10-26 15:26 UTC, piersy commented on cmd/autonity/chaincmd.go
>  func dumpGenesis(ctx *cli.Context) error {
If we are making this command invalid why not just fully remove this command?

2020-10-26 16:44 UTC, yazzaoui commented on cmd/autonity/chaincmd.go
>  func dumpGenesis(ctx *cli.Context) error {
I'll remove it.

2020-10-27 10:59 UTC, yazzaoui commented on p2p/server.go
> +}
I'll move it back in `server_transport.go` if you prefer, the thinking was that code used for test exclusively didn't warrant to be put in an exclusive, non-test, file.

2020-10-27 11:53 UTC, aneequesafdar approved these changes

2020-10-27 12:30 UTC, yazzaoui commented on metrics/meter.go
> +	ma.doneCh <- struct{}{}
Yeah

2020-10-27 12:34 UTC, yazzaoui commented on consensus/test/testcase_test.go
> +	log.Root().SetHandler(log.LvlFilterHandler(log.LvlDebug, log.StreamHandler(os.Stderr, log.TerminalFormat(true))))
For the CI logs, I'll revert that when we're happy with this branch.

2020-10-27 12:38 UTC, yazzaoui commented on consensus/consensus.go
> +	Seal(chain ChainReader, block *types.Block, results chan<- *types.Block, stop <-chan struct{}) error
I think `ChainHeaderReader` is only needed for light client support, validators calling `Seal` will always have access to the full blockchain object.

2020-10-28 10:46 UTC, Jason-Zhangxin-Chen approved these changes

2020-10-28 10:50 UTC, piersy commented on consensus/consensus.go
> +	Seal(chain ChainReader, block *types.Block, results chan<- *types.Block, stop <-chan struct{}) error
What do we do when we wan't to support light clients then? I thought this was fairly close on our roadmap.

2020-10-28 10:53 UTC, piersy commented on p2p/server.go
> +}
> I'll move it back in `server_transport.go` if you prefer, the thinking was that code used for test exclusively didn't warrant to be put in an exclusive, non-test, file.

I'm not following, code used for tests exclusively should be in a test file or a test package. I thought you said we couldn't move this back to the test file easily? If we can then lets do it. Otherwise I'd like to understand why you moved this out of the test file?

2020-10-28 12:27 UTC, yazzaoui commented on p2p/server.go
> +}
> I'm not following, code used for tests exclusively should be in a test file or a test package.

Totally agree but doing so here is not in the scope of this PR.

>Otherwise I'd like to understand why you moved this out of the test file?

It was like this before, see https://github.com/clearmatics/autonity/blob/develop/p2p/server_transport.go

2020-10-28 12:27 UTC, yazzaoui commented on consensus/consensus.go
> +	Seal(chain ChainReader, block *types.Block, results chan<- *types.Block, stop <-chan struct{}) error
`Seal` is only called from the miner package so not from light clients.

2020-10-28 13:09 UTC, piersy commented on p2p/server.go
> +}
So the comment confused me

>// testTransport was moved from server_test.go as a temporary workaround around import issues.

But I would definitely move it back, being in a separate file that go-ethereum doesn't have means it cant conflict with their changes. As it stands changes to server.go could now conflict with this.

2020-10-28 13:13 UTC, piersy commented on consensus/consensus.go
> +	Seal(chain ChainReader, block *types.Block, results chan<- *types.Block, stop <-chan struct{}) error
Ahh ok.

2020-10-28 13:30 UTC, yazzaoui commented on p2p/server.go
> +}
Fair enough, already done it yesterday.

2020-10-28 15:41 UTC, piersy approved these changes
Lets merge it.

2020-10-28 19:29 UTC, merged