Future proposal consensus fix
clearmatics/autonity pull request #722
Opened 2020-11-02 20:33 UTC by yazzaoui

- Fix future proposal handling: A bug in the handling of future proposals was spotted in the DevNet. The engine was incorrectly moving to the prevote round and setting the proposal for the current round as nil which was leading the node to hang and not be able to commit even though it received a quorum of precommits for a valid proposal. 

- Renaming of dumpEconomicMetrics method which was forgotten.

Signed-off-by: yazzaoui <ya@clearmatics.com>

2020-11-03 09:08 UTC, piersy approved these changes

2020-11-03 09:09 UTC, piersy requested changes
Actually I was too hasty, the tests are failing

2020-11-03 10:41 UTC, Jason-Zhangxin-Chen approved these changes
LGTM

2020-11-03 14:59 UTC, piersy commented on consensus/tendermint/core/propose.go
> +			return err
I don't see that we have a test for this error.

2020-11-03 15:03 UTC, piersy commented on consensus/tendermint/core/propose.go
> +
I don't see that we have a test for this either.

2020-11-03 17:12 UTC, yazzaoui commented on consensus/tendermint/core/propose.go
> +			return err
`"future proposal given, backlog event posted"` is checking it.

2020-11-03 17:13 UTC, yazzaoui commented on consensus/tendermint/core/propose.go
> +
I'll add one.

2020-11-04 14:47 UTC, piersy commented on consensus/tendermint/core/propose_test.go
> +		<-time.NewTimer(2 * time.Second).C
What is going on here ?

2020-11-04 17:56 UTC, yazzaoui commented on consensus/tendermint/core/propose_test.go
> +		<-time.NewTimer(2 * time.Second).C
We have a one second timer before we expect the `backlog` event with the proposal to be posted, so waiting for that to happen here.

2020-11-05 12:10 UTC, piersy commented on consensus/tendermint/core/propose_test.go
> +		<-time.NewTimer(2 * time.Second).C
Why do we care? This is the last line of the test, nothing happens after it.

2020-11-05 13:44 UTC, yazzaoui commented on consensus/tendermint/core/propose_test.go
> +		<-time.NewTimer(2 * time.Second).C
The `backendMock.EXPECT().Post(event).Times(1)` (L311) would fail if we return too quickly.

2020-11-05 14:55 UTC, piersy commented on consensus/tendermint/core/propose_test.go
> +		<-time.NewTimer(2 * time.Second).C
I think you could add some comments to make this much clearer, as it stands its really not clear. You need to understand that returning 1s from VerifyProposal will cause the message to be posted after 1s and then you need to realise that we are waiting for that to happen.

2020-11-06 18:32 UTC, piersy approved these changes
Looking good now :+1:

2020-11-06 19:01 UTC, merged